# Generated by Django 2.1.4 on 2018-12-13 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slackforms', '0012_auto_20181213_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='The name of your token.', max_length=100, unique=True)),
                ('token', models.SlugField(editable=False, max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='form',
            name='endpoint',
            field=models.URLField(blank=True, help_text='A URL to hit with the processed and validated form data.', null=True),
        ),
        migrations.DeleteModel(
            name='Endpoint',
        ),
        migrations.AddField(
            model_name='form',
            name='token',
            field=models.ForeignKey(blank=True, help_text='A token to send with the endpoint.', null=True, on_delete=django.db.models.deletion.PROTECT, to='slackforms.Token'),
        ),
    ]
